version: "3"

services:
    app:
        build:
            context: .
        volumes:
            - ./src:/usr/local/src/blockchain
        command: sh -c "python app.py"
        ports:
            - "80:5000"
        depends_on:
            - db
    db:
        image: mysql
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: 'example'
            MYSQL_DATABASE: 'crypto'
        volumes:
            - ".data/mysql:/var/lib/mysql"
            - "./dump/:/docker-entrypoint-initdb.d"


