version: "3"

services:
    app:
        build:
            context: .
        volumes:
            - ./src:/usr/local/src/blockchain
        command: sh -c "python blockchain.py"

    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
